### PR TITLE
make emails in list collapsible

### PR DESCRIPTION
**Pull request by pilpul**
just added some classes and links so mails are collapsible (default is not collapsed); based on bootstrap.
makes navigating easier for addresses with multiple and/or longer mails.

### CODE REVIEW

**Comment by synox** [comment]
cool! do you also use https://github.com/synox/disposable-email-imap ?

**Comment by pilpul** [comment]
no didn't try that, yet. I have configured exim on my server to pipe the mail to php and that works fine.

**Comment by synox** [comment]
that's good. i had once in a while that the parser crashed and the email was lost because of that. In imap there is less that could go wrong (and is easier to configure for most users)

**Comment by pilpul** [comment]
I'll have a look later. thanks for the effort!

**Pull request merged**
